version: '3.1'
services:
  unity:
    container_name: unity_server
    image: ghcr.io/sepanou/unity-server:latest
    restart: unless-stopped
    ports:
      - "7777:7777/udp"
    volumes:
      - "./game_data:/root/.config/unity3d/Sépanou/Terres de l'Exil"
